version: '3.8'

services:
  chatbot:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=src.web_embed_generator
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
    volumes:
      - ./src:/app/src:rw
      - ./src/static:/app/src/static:rw
      - ./src/templates:/app/src/templates:rw
      - ./data:/app/data:rw
      - ./config:/app/config:rw
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
